### ISSUE TITLE
mapviewer gives segmentation fault

### ISSUE THREAD

**Issue by semicarbazid** [malasiot/maplite#8]
starting the mapviewer results in the following output:

```
ok here
Segmentation fault (core dumped)
```
Can this be related to the fact, that I have no config file present?

**Comment by Freeviv** [comment]
Got the same problem. Here is the GDB output

`Thread 1 "mapviewer" received signal SIGSEGV, Segmentation fault.
0x00007ffff44ab287 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff44ab287 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
    at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000555555773845 in RenderTheme::defaultLayer[abi:cxx11]() const (this=0x0) at /home/janschon/tmp/maplite/src/renderer/theme.hpp:46
#2  0x0000555555770a8e in MainWindow::readAppSettings() (this=0x7fffffffda20) at /home/janschon/tmp/maplite/src/viewer/main_window.cpp:370
#3  0x000055555576d26f in MainWindow::MainWindow(int&, char**) (this=0x7fffffffda20, argc=@0x7fffffffda0c: 1, argv=0x7fffffffdd48) at /home/janschon/tmp/maplite/src/viewer/main_window.cpp:63
#4  0x0000555555767285 in main(int, char**) (argc=1, argv=0x7fffffffdd48) at /home/janschon/tmp/maplite/src/viewer/viewer.cpp:83
`
